### ISSUE TITLE
DecodeViaWasmClientState still references old strategy in CanDecode<Any, ...> trait

### ISSUE THREAD

**Issue by vaporif** [informalsystems/hermes-sdk#452]
## Summary of Bug
Hello, I've noticed a small error after [Encoding context refactoring #410](https://github.com/informalsystems/hermes-sdk/pull/410) where strategy `Any` was changed to `ViaAny` and wasn't updated in
https://github.com/informalsystems/hermes-sdk/blob/34c0d461a473b43a3d797b8dd18035714e4dd557/crates/wasm/wasm-encoding-components/src/impls/strategies/client_state.rs#L29
This should be `CanDecode<ViaAny, ...>`

## Version
Hermes sdk commit `fc29e42`, ibc-rs 0.54 and also unfixed in current main

## Steps to Reproduce

Try to use `DecodeViaWasmClientState` in cgp

## Acceptance Criteria

A simple fix 
```
impl<Encoding, Value> Decoder<Encoding, WasmClientState, Value> for DecodeViaWasmClientState
where
    Encoding: HasEncodedType<Encoded = Vec<u8>>
        + CanDecode<ViaAny, WasmClientState>
        + CanDecode<ViaAny, Value>,
{
    fn decode(encoding: &Encoding, encoded: &Vec<u8>) -> Result<Value, Encoding::Error> {
        let wasm_client_state: WasmClientState = encoding.decode(encoded)?;

        let value: Value = encoding.decode(&wasm_client_state.data)?;

        Ok(value)
    }
}

```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by soareschen** [comment]
Thanks for the catch! It looks like the implementation is no longer used in the current code base, and thus we can probably remove that.

The issue is that there is an asymetry around the encoding and decoding of Wasm-wrapped client states, as the encoding part requires an additional Wasm code hash field. As a result, it is better to use Wasm-wrapped types such as `WasmTendermintClientState`, instead of the base type `TendermintClientState` as the `ClientState` type. You can find out how it is implemented [here](https://github.com/informalsystems/hermes-sdk/blob/main/crates/cosmos/cosmos-wasm-relayer/src/types/client_state.rs).

In any case, since the implementation is fully decoupled, you can easily copy the original `DecodeViaWasmClientState` to your code base and customize it there. On the Hermes SDK side, I would probably remove that and introduce a helper type like `WasmClientState<ClientState>` to help with conversion implementation.

**Comment by vaporif** [comment]
@soareschen 
thanks!
